services:
    app:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        image: bookworm-app
        ports:
            - '${APP_PORT:-8001}:80'
        environment:
            APACHE_DOCUMENT_ROOT: /var/www/html/public
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        extra_hosts:
            - 'host.docker.internal:host-gateway'
networks:
    sail:
        driver: bridge
